# name: Create Release and PR to Main

# on:
#   push:
#     branches:
#       - developer

# jobs:
#   release:
#     if: github.actor != 'github-actions[bot]'  # ⛔ Impede loop de execução automática
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3
#         with:
#           token: ${{ secrets.CI_ADMIN_TOKEN }}  # Seu PAT com permissão de escrita

#       - name: Setup Git
#         run: |
#           git config user.name "github-actions[bot]"
#           git config user.email "github-actions[bot]@users.noreply.github.com"

#       - name: Read and bump version
#         id: bump_version
#         run: |
#           OLD_VERSION=$(cat version.txt)
#           echo "Versão atual: $OLD_VERSION"
#           IFS='.' read -r MAJOR MINOR PATCH <<< "$OLD_VERSION"
#           PATCH=$((PATCH + 1))
#           NEW_VERSION="$MAJOR.$MINOR.$PATCH"
#           echo "$NEW_VERSION" > version.txt
#           echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT

#       - name: Commit updated version.txt
#         run: |
#           git add version.txt
#           git commit -m "chore: bump version to v${{ steps.bump_version.outputs.version }}"
#           git push origin developer
#         env:
#           GITHUB_TOKEN: ${{ secrets.CI_ADMIN_TOKEN }}

#       - name: Create release branch
#         run: |
#           git checkout -b release/v${{ steps.bump_version.outputs.version }}
#           git push origin release/v${{ steps.bump_version.outputs.version }}
#         env:
#           GITHUB_TOKEN: ${{ secrets.CI_ADMIN_TOKEN }}

#       - name: Create GitHub Release
#         uses: softprops/action-gh-release@v1
#         with:
#           tag_name: v${{ steps.bump_version.outputs.version }}
#           name: Release v${{ steps.bump_version.outputs.version }}
#         env:
#           GITHUB_TOKEN: ${{ secrets.CI_ADMIN_TOKEN }}

#       - name: Create Pull Request to main
#         uses: peter-evans/create-pull-request@v5
#         with:
#           token: ${{ secrets.CI_ADMIN_TOKEN }}
#           source: release/v${{ steps.bump_version.outputs.version }}
#           target: main
#           title: "Release v${{ steps.bump_version.outputs.version }}"
#           body: "Pull request automático gerado a partir da branch developer."
